### ISSUE TITLE
Rustdesk says remote machine is offline while it's up and running

### ISSUE THREAD

**Issue by mtelis** [rustdesk/rustdesk#2207]
It takes numerous attempts until I finally connect to the remote. Then, if I need to transfer files, I can't open the "Transfer file" window even though I'm connected to and interacting with the same remote machine just fine.

I'm running Ver. 1.1.9 on both local and remote PCs, my machine is running Win 10 while the remotes (I observed this behavior with several remote machines) are running Win 7 or Win 10.

Eventually, I can open the Transfer file window but again, it takes a lot of attempts and patience.
![Remote desktop is offline](https://user-images.githubusercontent.com/335301/202698610-fbfc8a77-1c79-4172-aecb-b890b0d7738b.png)

**Comment by jctmf** [comment]
Same problem

**Comment by rustdesk** [comment]
@21pages could you help reproduce this problem?

**Comment by 21pages** [comment]
let me try

**Comment by FCrane** [comment]
I have the same problem - it's happening extremely often. Especially when trying to connect to an Android device from Windows 11. In my LAN, I fixed it by connecting to an IP address, which seems to work reliably). However, the Android client does not seem to support connecting to its IP address...

**Comment by mtelis** [comment]
Not sure if it's related, but when the Transfer file window finally opens, its right (remote computer) panel shows "C:\Windows\ServiceProfiles\LocalService\" directory instead of the directory I left off on the previous session.

**Comment by rustdesk** [comment]
slefhost please, our 10$/month server is overloaded lately.

**Comment by FCrane** [comment]
Please update the Android app so that it accepts direct IP connections...

**Comment by LazerDickMcCheese** [comment]
This problem still exists, Rustdesk was working for me consistently until this past week. Now I have to completely uninstall Rustdesk from both machines, restart, then reinstall on both. If I close the connection, I have to repeat that process to get into my machine.

**Comment by sirpawulo** [comment]
same problem here, haventb been able to get it to work even once. please help!

**Comment by sepsol** [comment]
Same here. I'm running rustdesk service on Nokia 1.4. The app is excluded form battery optimization. I have checked the app's settings and enabled anything that would prevent the service from being killed. Yet, it's still stopped for some reason.

**Comment by DovieW** [comment]
same issue

**Comment by jordanhardee** [comment]
Same issue (minus transfer file part, this is untested)

**Comment by amphyvi** [comment]
Same issue. I'm getting it while using my own self-hosted server, too. Incredibly weird.
