### ISSUE TITLE
Cannot re-open RustDesk on Mac after closing it if service is installed

### ISSUE THREAD

**Issue by breathless19** [rustdesk/rustdesk#3369]
### Bug Description

Apple M1 Mac Mini.... Ventura 13.2.1

Cannot re-open RustDesk on Mac after closing it if service is installed.    Reboot is required in order to open it again.  

### How to Reproduce

If you open RustDesk client... don't install service.   Close RustDesk.   Reopen RustDesk to your hearts content... No problem. 

However, open the client and install service to enable auto starting on reboot, service is installed, close RustDesk.   RustDesk cannot be reopened until reboot.   Clicking on the icon does nothing. 

### Expected Behavior

RustDesk should be able to close and reopen as many times as one would like. 

### Operating system(s) on local side and remote side

Ventura 13.2.1

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

.

**Comment by rustdesk** [comment]
@Kingtous

**Comment by rustdesk** [comment]
Close as fix merged

**Comment by Lighfer** [comment]
1.2.1 still has this problem, I have to reopen throught terminal
```shell
open -n /Applications/RustDesk.app
```

**Comment by rustdesk** [comment]
it works well on my mac

**Comment by Kingtous** [comment]
> @rustdesk 1.2.1 still has this problem, I have to reopen through terminal
> 
> ```shell
> open -n /Applications/RustDesk.app
> ```

plz try uninstalling the service and reinstall it?

**Comment by godzfire** [comment]
Still occurring on 1.2.2 release. Only way to open is using the terminal command above.

Mac Mini, OS Monetary 12.6.8 Intel

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/5631#discussioncomment-6943538

**Comment by nsby7c** [comment]
I'm having the same issue after initial install. Only terminal command will open it, but will open from the installer image without issues. Only after being placed in applications do problems arise.

**Comment by godzfire** [comment]
Why was this closed? This is still happening as of 1.2.3.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/commit/d407dfed0a18289a77acf1cc3211c32eeec08fde
https://github.com/rustdesk/rustdesk/commit/85f387bfb9ec2a8067d3273829a21b1deb07efd4

**Comment by SachaRoland** [comment]
Hey, 
I have downloaded Rustdesk 1.3.2 on a Mac Monterey but cannot open it or at least get the display started. 
I have tried the basics: restarting the computer, uninstalling-reinstalling, nothing change. 
I gave all permissions for the app to open but nothing happens when I click on it. 

Any tip please???
