### ISSUE TITLE
Black Screen to Linux Machine (Update: Underscan appears to be a problem setting)

### ISSUE THREAD

**Issue by robert-stevenson-1** [rustdesk/rustdesk#7354]
### Bug Description

[Unexpected situation Update (See comment)](https://github.com/rustdesk/rustdesk/issues/7354#issuecomment-1987373386)

When remoting into my Linux desktop, I am met with a black screen with nothing visible.
I do still have input control however, just no visual information.

My desktop is running (currently): linux Mint 21.3 
(Was on 21.2 before upgrading to see is wayland did anything)
I am also using an Nvidia gpu (RTX3060ti)

I've tried Nvidia Driver versions:
- 545
- 535
- 525
- 470
- nouveau (open-source drivers)

I have tried Rustdesk versions:
- 1.2.0
- 1.2.3
- 1.2.4 (nightly)
- 1.2.3 (under wayland)
- 1.2.4 (nightly)  (under wayland)
- 1.9.0

Version 1.9.0 Still works (with both machines needing to using this version) and only 1.2.0+ works when using the nouveau drivers.

### How to Reproduce

- Install Rustdesk 1.2.0 (or greater)
- Remote into the Linux machine that's using an Nvidia GPU
- Connected Shows a Blank, Black, screen

### Expected Behavior

View of my desktop (and applications) running on my Linux desktop via the remote client

### Operating system(s) on local side and remote side

Linux (Mint 21.2) & Windows 10 -> Linux (Mint 21.2 & 21.3)

### RustDesk Version(s) on local side and remote side

1.2.0 (or greater)

### Screenshots

Working 1.9.0
![image](https://github.com/rustdesk/rustdesk/assets/78357805/67dfdfe9-cd3c-4e43-8358-7e5c8ff4de90)

**Comment by robert-stevenson-1** [comment]
**Update**

Was just collecting a screenshot for showing the blank, black, window using 1.2.3 (on both device) and the desktop is now being displayed.

This involved updating Rustdesk from 1.9.0 -> 1.2.3.

Why this has happened is unknown.

There is, however, now some artifacting in the window that is not present on the actual desktop and is therefore in Rustdesk (See image)
 
![image](https://github.com/rustdesk/rustdesk/assets/78357805/7b01ab90-5e84-4c52-baf3-efe7c78133dd)

**Comment by robert-stevenson-1** [comment]
**Update 2:**
The Issue appears to stem from some of my Nvidia settings and having any form of underscan enabled.

Not sure if this applies to another graphic drivers, this would need testing by others.

Also unsure if this is something that be fixed in rustdesk

**Comment by rustdesk** [comment]
tracked by https://github.com/rustdesk/rustdesk/issues/3565

**Comment by crobs808** [comment]
This is still happening on the latest RustDesk I just downloaded a few days ago on both the server and client computer.
- Client (connecting from MacOS)
- Server, target computer (Linux Mint 22.2)

I read something about setting `WaylandEnable=False` in `/etc/gdm3/custom.conf`, but I cannot get to that file from remote since the Terminal (beta) feature in RustDesk doesn't let you traverse outside the user directory :(

I am wondering if that's not really the issue though, based on the "Update 2" above from 2024 related to Nvidia underscanning. Any updates on this? I am currently remote and got the black screen so I cannot do anything until I am home anyway.
