### ISSUE TITLE
Can not login when the controlled device is Ubuntu 24.04 on Wayland

### ISSUE THREAD

**Issue by goxq** [rustdesk/rustdesk#8153]
### Bug Description

I'm using the latest version of rustdesk on Mac controlling ubuntu 24.04 on wayland.
It's fine but when I lock the screen on Ubuntu (Super + L), I can not connect the ubuntu again. I must input the password to login directly on the Ubuntu and I need to confirm "choose which screen to record" again..

### How to Reproduce

in bug description

### Expected Behavior

in bug description

### Operating system(s) on local side and remote side

mac -> ubuntu 24.04

### RustDesk Version(s) on local side and remote side

1.23

### Screenshots

no

**Comment by rustdesk** [comment]
fixed in nightly build

**Comment by rustdesk** [comment]
login screen not support for wayland

**Comment by goxq** [comment]
> login screen not support for wayland

will it support in the future?

**Comment by ikerib** [comment]
will be?

**Comment by Lykr** [comment]
It seems that Wayland is still not supported after about 1 year.
